# Google Cloud Run 服务配置
# 用于声明式部署和管理ByteC Postback服务

apiVersion: serving.knative.dev/v1
kind: Service
metadata:
  name: bytec-postback
  labels:
    app: bytec-postback
    environment: production
    tier: backend
  annotations:
    run.googleapis.com/ingress: all
    run.googleapis.com/ingress-status: all
    # 启用全球负载均衡器
    run.googleapis.com/cpu-throttling: "false"
    # 允许二进制响应
    run.googleapis.com/binary-authorization: "disabled"
spec:
  template:
    metadata:
      labels:
        app: bytec-postback
        version: "v1"
      annotations:
        # 自动扩缩容配置
        autoscaling.knative.dev/maxScale: "20"
        autoscaling.knative.dev/minScale: "0"
        # 资源限制
        run.googleapis.com/memory: "512Mi"
        run.googleapis.com/cpu: "1000m"
        # 网络配置
        run.googleapis.com/vpc-access-connector: ""
        run.googleapis.com/vpc-access-egress: "private-ranges-only"
        # 执行环境
        run.googleapis.com/execution-environment: gen2
    spec:
      # 容器超时时间
      timeoutSeconds: 300
      # 服务账号
      serviceAccountName: bytec-postback-sa
      # 容器配置
      containers:
      - name: bytec-postback
        # 镜像地址（部署时会被替换）
        image: gcr.io/PROJECT_ID/bytec-postback:latest
        # 端口配置
        ports:
        - name: http1
          containerPort: 8080
          protocol: TCP
        # 环境变量
        env:
        # 基础配置
        - name: PORT
          value: "8080"
        - name: DEBUG
          value: "false"
        - name: LOG_LEVEL
          value: "INFO"
        - name: HOST
          value: "0.0.0.0"
        - name: WORKERS
          value: "1"
        - name: THREADS
          value: "8"
        
        # 应用配置
        - name: APP_NAME
          value: "ByteC Postback API"
        - name: APP_VERSION
          value: "1.0.0"
        - name: ENVIRONMENT
          value: "production"
        
        # 数据库配置（从Secret获取）
        - name: DATABASE_URL
          valueFrom:
            secretKeyRef:
              key: database-url
              name: bytec-postback-secrets
        - name: DATABASE_ECHO
          value: "false"
        
        # Redis配置（可选）
        - name: REDIS_URL
          valueFrom:
            secretKeyRef:
              key: redis-url
              name: bytec-postback-secrets
              optional: true
        
        # Token配置
        - name: TS_TOKEN_SECRET
          valueFrom:
            secretKeyRef:
              key: ts-token-secret
              name: bytec-postback-secrets
        - name: TLM_TOKEN_SECRET
          valueFrom:
            secretKeyRef:
              key: tlm-token-secret
              name: bytec-postback-secrets
        
        # 业务配置
        - name: DATA_RETENTION_DAYS
          value: "30"
        - name: MAX_REQUESTS_PER_MINUTE
          value: "1000"
        - name: ENABLE_DUPLICATE_CHECK
          value: "true"
        
        # 监控配置
        - name: ENABLE_METRICS
          value: "true"
        - name: METRICS_PORT
          value: "8001"
        
        # 资源限制
        resources:
          limits:
            cpu: 1000m
            memory: 512Mi
          requests:
            cpu: 100m
            memory: 128Mi
        
        # 启动探针
        startupProbe:
          httpGet:
            path: /postback/health
            port: 8080
            httpHeaders:
            - name: User-Agent
              value: "GoogleCloudRun/StartupProbe"
          initialDelaySeconds: 10
          periodSeconds: 3
          timeoutSeconds: 3
          failureThreshold: 10
          successThreshold: 1
        
        # 存活探针
        livenessProbe:
          httpGet:
            path: /postback/health
            port: 8080
            httpHeaders:
            - name: User-Agent
              value: "GoogleCloudRun/LivenessProbe"
          initialDelaySeconds: 30
          periodSeconds: 30
          timeoutSeconds: 5
          failureThreshold: 3
          successThreshold: 1
        
        # 就绪探针
        readinessProbe:
          httpGet:
            path: /postback/health
            port: 8080
            httpHeaders:
            - name: User-Agent
              value: "GoogleCloudRun/ReadinessProbe"
          initialDelaySeconds: 5
          periodSeconds: 10
          timeoutSeconds: 3
          failureThreshold: 3
          successThreshold: 1
        
        # 安全上下文
        securityContext:
          runAsNonRoot: true
          runAsUser: 1000
          allowPrivilegeEscalation: false
          capabilities:
            drop:
            - ALL
          readOnlyRootFilesystem: false
      
      # 并发设置
      containerConcurrency: 100 