name = "bytec-postback-proxy"
main = "cloudflare-worker-ready.js"
compatibility_date = "2024-07-01"
compatibility_flags = ["nodejs_compat"]

[vars]
ENVIRONMENT = "development"

# 生产环境变量（可选）
# [env.production.vars]
# ENVIRONMENT = "production"
# BACKEND_URL = "https://your-production-server.com"

# 自定义域名配置（可选）
# [[route]]
# pattern = "network.bytec.com/involve/*"
# zone_name = "bytec.com"

# 开发环境域名配置（默认使用workers.dev）
# 部署后将获得：https://bytec-postback-proxy.你的用户名.workers.dev

# Worker设置
[build]
command = ""

# 限制和配置 (免费计划暂时移除CPU限制)
# [limits]
# cpu_ms = 10000

# 日志配置
[observability]
enabled = true 